08049f14 d _DYNAMIC
0804a000 d _GLOBAL_OFFSET_TABLE_
0804848c R _IO_stdin_used
         w _ITM_deregisterTMCloneTable
         w _ITM_registerTMCloneTable
         w _Jv_RegisterClasses
08048578 r __FRAME_END__
08048490 r __GNU_EH_FRAME_HDR
08049f10 d __JCR_END__
08049f10 d __JCR_LIST__
0804a018 D __TMC_END__
0804a018 B __bss_start
0804a010 D __data_start
08048390 t __do_global_dtors_aux
08049f0c t __do_global_dtors_aux_fini_array_entry
0804a014 D __dso_handle
08049f08 t __frame_dummy_init_array_entry
         w __gmon_start__
08049f0c t __init_array_end
08049f08 t __init_array_start
08048470 T __libc_csu_fini
08048410 T __libc_csu_init
         U __libc_start_main@@GLIBC_2.0
08048310 T __x86.get_pc_thunk.bx
0804a018 D _edata
0804a01c B _end
08048474 T _fini
08048488 R _fp_hw
0804828c T _init
080482e0 T _start
0804a018 b completed.7209
0804a010 W data_start
08048320 t deregister_tm_clones
080483b0 t frame_dummy
080483db T main
08048350 t register_tm_clones
